import swaggerJsdoc from "swagger-jsdoc";
import swaggerUi from "swagger-ui-express";

const options = {
  swaggerDefinition: {
    info: {
      title: "Test API",
      version: "1.0.0",
      description: "Test Express API with autogenerated swagger doc"
    }, 
    basePath: "/v1"
  },
  apis: ["./router/**/*.js"]
};

const specs = swaggerJsdoc(options);

const swaggerDoc = app => {
  app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(specs));
};

export default swaggerDoc;
